-- V7: the second half of the 2026-09-04 foreign crawl (AT/CZ/PL/SI/SK).
--
-- V6 (migration 20260905000746) landed the 14 hosts that had cleared BOTH the
-- proposing and the adversarial verifying pass. The remaining 25 hosts had only
-- ever been seen by the proposing pass — that run hit its weekly agent limit — so
-- they were deliberately left out. This migration carries the survivors of the
-- verifying pass that was owed to them, plus the three hosts (oeticket.com,
-- ticketportal.cz, eventim.pl) that never got a first pass either and were
-- therefore vetted here from scratch.
--
-- Why the second pass is not ceremony: on the Hungarian V5 run it rejected 11 of
-- 39 first-pass proposals and corrected another 10. This round it rejected 8 of
-- the 28 hosts — a 29% failure rate among candidates a single pass had cleared:
--
--   kosice.sk              A hub article, not a calendar: 3-4 events, and their
--                          dates (May/June 2026) are already in the past.
--                          (The first pass also said reject; independently upheld.)
--   opera.si               /sl/program/koledar/ is a client-rendered shell —
--                          HTTP 200 but 1.2 KB of text, zero events, an
--                          eventList.bundle.js and a data-startdate attribute.
--                          /sl/repertoar/ lists works without dates. The house's
--                          dated performances reach us through mojekarte.si
--                          below, which is where opera.si itself sells tickets.
--   salzburgerfestspiele.at  /karten/kalender is likewise a JS shell (1.4 KB of
--                          text, no events); the 2026 festival ended 30 August
--                          and the 2027 edition is not on sale.
--   ticketportal.sk        Server HTML is an untranslated SPA template: literal
--   ticketportal.cz        [SK|lbKategorie] and %ValidDate% placeholders, Lorem
--                          ipsum, a 2017 demo event. Zero 2026/2027 date tokens
--                          and zero JSON-LD in the whole document, on both hosts.
--   eventim.si             Unreachable. curl with a browser UA over IPv4 and
--   oeticket.com           IPv6, and WebFetch — two independent egress paths —
--   eventim.pl             all time out or get the connection reset. The V5
--                          lesson stands: no live fetch, no source.
--
-- Each of the 20 rows below was re-fetched here and shown to list MULTIPLE dated
-- events, and its robots.txt was read on the serving host. Hence
-- review_state='approved', legal_review_status='approved', robots_allowed=true.
-- `enabled` stays false — that column drives the legacy no-JS feed pipeline; the
-- Playwright worker reads scrape_enabled.
--
-- ONE ROW IS DELIBERATELY DIFFERENT: www.wien.info is approved but ships with
-- scrape_enabled=false. Its endpoint is a genuinely excellent source (one GET
-- returns ~425 KB of JSON covering the whole forward calendar) but the payload is
-- a bespoke {items:[...]} shape. None of the worker's strategies can read it:
-- 'jsonld' requires <script type="application/ld+json"> tags, 'wp-posts' expects
-- the WordPress REST shape, and 'render' would drive Playwright at a JSON
-- document. Enabling it would only accrue consecutive_failures. It is registered
-- so the endpoint and its robots clearance are not lost; flip scrape_enabled once
-- a 'site' adapter or a json-items strategy exists.

INSERT INTO public.external_event_feed_sources (
  source_id, publisher_name, publisher_type, city, country_code, endpoint_url,
  original_endpoint_url, format, categories, legal_basis, audit_status,
  dedupe_priority, parser_strategy, notes, fetch_hosts,
  review_state, legal_review_status, robots_allowed, enabled, scrape_enabled, scrape_strategy
)
SELECT
  v.source_id, v.publisher_name, NULL, v.city, v.country_code, v.endpoint_url,
  v.endpoint_url, v.format, v.categories, v.legal_basis, NULL,
  v.dedupe_priority, v.parser_strategy,
  'Discovered by the 2026-09-04 foreign crawl; endpoint and robots.txt verified by two independent live fetches (proposing pass 2026-09-04, verifying pass 2026-09-05).',
  ARRAY[v.host],
  'approved', 'approved', true, false, v.scrape_enabled, v.scrape_strategy
FROM (VALUES

  -- ============================== AT ==============================
  ('events.at (k-digital Medien GmbH & Co KG, KURIER-Gruppe)','Österreichweit','AT','https://events.at/calendar','HTML event listing',ARRAY['Konzerte','Theater','Kabarett','Musical','Ausstellungen','Party/Clubbing','Festivals','Kinder/Familie'],'robots.txt (HTTP 200) has a single "User-agent: *" group disallowing only /search, /themen/*/* and /preview/*; /calendar, the category listings and /event/* are all permitted, and no Crawl-delay is declared. Five XML sitemaps (events, venues, artists, articles, news) are advertised, which invites machine discovery. Ingest factual metadata only (title, date, venue, city, detail URL) and deep-link back.',0,'MUST send a desktop Chrome User-Agent: WebFetch and plain Node fetch both get HTTP 403, while curl with a browser UA plus Accept-Language: de-AT returns 200 every time. Server-rendered HTML, no JS. /calendar renders ~10 cards behind a numbered pager ("1 2 3 4 ... 6 Weiter") — verified live: 04-05 Sep 2026 Oage Tekke @ Arena Wien, 05 Sep 2026 DINOLAND @ Schloss Katzenberg, Schlossberg-Rundgang @ Schlossberg Graz, Vorführungen @ Spanische Hofreitschule. No JSON-LD on listing pages: parse the DOM, where each card carries <time datetime="YYYY-MM-DD HH:mm">, the title, the venue and an href /event/<slug>. For volume prefer the category listings (/konzerte alone yielded 257 event links) or enumerate https://events.at/sitemaps_event.xml. CAUTION: the listing also carries evergreen rows with absurd end dates (an exhibition running to "06 Feb 2202", a yoga studio to 2036) — clamp end_date for sanity. Timezone Europe/Vienna.','events.at','src_44a5e541',true,'render'),

  ('Linz-Termine (Magistrat Linz, Kommunikation und Marketing)','Linz','AT','https://www.linztermine.at/suche','HTML event listing',ARRAY['Musik','Kunst & Kultur','Freizeit & Unterhaltung','Sport & Bewegung','Diverses'],'robots.txt (HTTP 200): "User-agent: *" disallows only /at.linztermine.admin and /javax.faces.resource, so /suche, the category .xhtml listings and /event/* are permitted, with no Crawl-delay. The named blanket blocks target SEO and marketing bots only (AhrefsBot, SemrushBot, serpstatbot, MJ12bot, PetalBot, MetaJobBot, ecoresearchCrawler); nothing targets generic or AI crawlers. Public-sector city information service; the listings are factual data. Rate-limit politely, use a truthful UA, do not reuse event photos, and link back to /event/{id}.',1,'Static server-rendered HTML (JSF/PrimeFaces), no JS. Verified live: /suche reported "1636 Veranstaltungen für dich gefunden" with dated rows — Thai Festival 05.09.2026, Kinder Klangwolke 26 06.09.2026 @ Donaupark, Ars Electronica Festival 09.-13.09.2026 @ Linz Innenstadt. Row selector a.event-row[href^="/event/"]; title in a descendant h3.h6; date DD.MM.YYYY with an optional preceding "bis " span marking a multi-day run; venue follows the #icon-pin svg. Each listing renders only 15 rows and the "more" control is a PrimeFaces AJAX POST — do NOT try GET pagination; fan out over /musik.xhtml, /kunst-kultur.xhtml, /freizeit-unterhaltung.xhtml, /sport-bewegung.xhtml, /diverses.xhtml and the ?when= date filters instead, then follow each /event/{id} link. The numeric {id} is a stable dedupe key. Ignore the ?sid= session token on links; content is de-AT only.','www.linztermine.at','src_4a917fb5',true,'render'),

  ('Musikverein Wien (Gesellschaft der Musikfreunde in Wien)','Wien','AT','https://spielplan.musikverein.at/spielplan','HTML event listing',ARRAY['Klassik','Konzert','Orchestermusik','Kammermusik','Chormusik','Alte Musik'],'musikverein.at/robots.txt is a Yoast block with "User-agent: * / Disallow:" (an empty Disallow, i.e. the whole site is permitted) advertising sitemap_index.xml. robots.txt is scoped per host, and the serving host spielplan.musikverein.at returns 404 for /robots.txt, i.e. default-allow. Collect factual metadata only (date, times, hall, title, performers, programme, organizer, plus a deep link back to musikverein.at/konzert/?id=...); do not republish editorial programme prose or press photos. Modest crawl rate — roughly 12 month-pages per refresh is enough.',0,'Static HTML, no headless browser. Verified live: the September 2026 page lists La Serenissima 05.09. 19:30 Gläserner Saal, Wiener Mozart Orchester 05.09. 20:15 Großer Saal, HYPNOTIC 06.09. 19:00 Brahms-Saal (marked Abgesagt), Wiener Philharmoniker 13.09. 19:30 Großer Saal. Iterate GET /spielplan?month=YYYY-MM over the options in the #month select (currently 2026-09 .. 2027-08) — re-read that select each run, never hardcode the range. Per event extract date DD.MM.YYYY, "HH:MM Uhr - HH:MM Uhr" split into start and end (Europe/Vienna), the hall, the fixed venue token "Musikverein", title, performers and the optional "Eingemietete Veranstaltung von: <promoter>" line (a rented, non-house event — that is the organizer). Dedupe on the 8-hex id in href="https://musikverein.at/konzert/?id=<id>"; each event renders TWO anchors with the same id, so group by id or the count doubles (165 anchors = 75 events). Honour the "Abgesagt" flag. Venue is fixed: Musikvereinsplatz 1, 1010 Wien (48.2003, 16.3726) — skip per-event geocoding. Do NOT point at musikverein.at/spielplan/ (a JS-only wrapper, 0 events server-side) or /kalender (404).','spielplan.musikverein.at','src_cea778be',true,'render'),

  ('Wiener Staatsoper','Wien','AT','https://www.wiener-staatsoper.at/kalender','HTML event listing',ARRAY['Oper','Ballett','Konzert','Klassik','Matinee','Kinder & Jugend'],'robots.txt permits the calendar for a generic agent: the Cloudflare-managed "User-agent: *" group is "Allow: /" and the second "User-agent: *" group disallows only /typo3/ and /typo3_src/; neither "kalender" nor "calendar" appears anywhere in the file. IMPORTANT CONSTRAINTS: the file Disallows a list of AI crawlers BY NAME (ClaudeBot, GPTBot, CCBot, Google-Extended, Amazonbot, Applebot-Extended, Bytespider, meta-externalagent, CloudflareBrowserRenderingCrawler), and sets "Content-Signal: search=yes, ai-train=no, use=reference" behind a preamble asserting these as express Article 4 EU DSM reservations. An event index that stores factual listing data and links users back falls under search=yes / use=reference, which the operator grants — PROVIDED the collector (a) runs under its own non-AI UA and never impersonates ClaudeBot or GPTBot, (b) is never used to train or fine-tune models on this content, and (c) stores only factual metadata, not synopses or images.',0,'Server-rendered TYPO3 HTML, no JS, but a browser-like User-Agent and Accept-Language are REQUIRED — default library UAs get a Cloudflare 403 (WebFetch did; curl with a Chrome UA returned 200). Verified live: /kalender 302s to /kalender/2026/september/ and reports "Anzahl der gelisteten Veranstaltungen: 34", with Fr. 04 Sep 19:00-22:30 Don Carlo (Großer Saal) and Sa. 05 Sep 19:00-22:15 Adriana Lecouvreur. No JSON-LD anywhere — parse the DOM. The bare /kalender redirect makes the base URL self-updating; walk forward with /kalender/{year}/{month-name-lowercase}/ (note the Austrian "jaenner"). Canonical key: the detail URL /kalender/detail/{slug}/{YYYY-MM-DD} — take the ISO date from the URL, not from the German day header, and dedupe on slug+date. CAUTION: day blocks embed a "weitere Termine" cast sidebar carrying dates from other months (159 dated links on a 33-event page), so filter to the month being crawled. Skip "keine Vorstellung" placeholder days. Pages are ~1.2 MB.','www.wiener-staatsoper.at','src_28c4b99e',true,'render'),

  ('WienTourismus (Vienna Tourist Board)','Wien','AT','https://www.wien.info/ajax/de/events','JSON (bespoke {items:[]} payload)',ARRAY['Konzerte klassisch','Oper und Operette','Rock/Pop/Jazz','Ausstellungen','Festivals und Shows','Theater und Kabarett','Märkte und Messen','LGBTIQ+'],'robots.txt permits it: under "User-agent: *" only /recommend$, /empfehlen$ and /feedback$ are disallowed — /ajax/ and /de/aktuell/ are unrestricted. The blanket "Disallow: /" rules apply solely to named commercial SEO crawlers (AhrefsBot, SemrushBot, SemrushBot-BM, MJ12bot, PetalBot, trendictionbot); Crawl-delay exists only for dotbot (10s) and bingbot (2s). Public-sector tourist board publishing event data for onward promotion. One request per run suffices — the whole calendar arrives in a single response.',1,'SHIPPED WITH scrape_enabled=false ON PURPOSE — the endpoint is verified and robots-clear, but no existing worker strategy can read it. Verified live: a GET with a browser UA returns HTTP 200, application/json, ~425 KB, shaped {"type":"events","items":[...]} — e.g. {"title":"Diversity Ball 2026","dates":["2026-09-05"],"location":"Wiener Rathaus"}, {"title":"Vienna Night Run 2026","dates":["2026-09-17"],"location":"Ringstraße"}, {"title":"Wien in Schwarz 2026","startDate":"2026-10-23","endDate":"2026-10-26"}. Per item: title, subtitle, startDate+endDate OR dates[] (handle BOTH forms), location, category, url (site-relative — prefix https://www.wien.info), imageUrl, id, and tags[] resolvable against the top-level filters array. All dates ISO. English mirror at /ajax/en/events. This is NOT JSON-LD, so the jsonld recipe cannot parse it, and it is not the WordPress REST shape either; it needs a small "site" adapter (or a json-items strategy) keyed on www.wien.info. Do NOT fall back to the HTML: /de/aktuell/veranstaltungen is a Vue SPA whose server HTML contains zero event dates.','www.wien.info','src_f3ebc4de',false,'render'),

  -- ============================== CZ ==============================
  ('Prague City Tourism, a.s. — official tourism authority of the City of Prague','Praha','CZ','https://prague.eu/cs/akce-kategorie/akce/','HTML event listing',ARRAY['koncerty','divadlo','výstavy','festivaly','trhy a gourmet','sport','rodina'],'/cs/akce-kategorie/akce/ is NOT disallowed for "User-agent: *". FOUR CONSTRAINTS THE COLLECTOR MUST HONOUR: (1) Crawl-delay: 600 — ten minutes between requests, by far the strictest in the registry; this endpoint suits it because one fetch yields ~870 events, so schedule a single daily hit and never a per-category or per-detail crawl. (2) Disallow: /*?* — every query-string URL is off limits, so no query-param pagination or filtering. (3) Disallow: /wp-json/ — the WordPress REST API must not be used. (4) CCBot, GPTBot and Google-Extended are each fully disallowed, so the collector must run under its own identifiable non-AI UA. Ingest factual metadata with attribution and link-back; do not copy editorial text or rehost the imgproxy.cdn.praguecitytourism.city images.',1,'Server-rendered HTML, a single request, no pagination needed. Verified live: ~870 events including Martinů. Barber. Beethoven 4.9.2026 19:30 @ Rudolfinum, Garáže Řepy 5.9.2026 10:00-16:00, Den letiště Letňany 5.9.2026, Prosecco Fest 5.9.2026 @ Villa Richter. Each event is a div.tile-switching card with machine-readable attributes: data-event_date="DD-MM-YYYY" (start), data-limitedend="DD-MM-YYYY" (end), data-poid=<stable numeric id, the dedupe key>, data-f_terms=<category term ids>. Inside: h2 > a[href] = title + canonical /cs/akce/<slug>, p = the human date/time string, span.tile-switching__afterHeading = venue. NO schema.org Event JSON-LD (the only ld+json block is CollectionPage/WebSite/Organization) — parse the DOM. Localised mirrors at /en/akce and /de/akce. IMPORTANT: /cs/akce 301s to the canonical URL above — point the collector at the canonical one to avoid a redirect hop, and remember that rule (2) forbids adding any query string.','prague.eu','src_7f71e014',true,'render'),

  ('Rudolfinum (Česká filharmonie / Galerie Rudolfinum)','Praha','CZ','https://www.rudolfinum.cz/program','HTML event listing',ARRAY['klasická hudba','koncerty','orchestr','komorní hudba','festivaly','výstavy'],'robots.txt is "User-agent: * / Disallow: /umbraco/" plus a sitemap — /program and /event are permitted and no Crawl-delay is declared, so apply a polite self-imposed rate. Publicly accessible listing published by the venue itself, no login or paywall. Ingest factual metadata only (date, time, hall, performer, title); deep-link back to the /event/ detail page and attribute Rudolfinum.',1,'Server-rendered HTML (Umbraco), no JSON-LD on the listing — parse the cards. Verified live: the Dvořákova Praha festival run — Zahajovací koncert Sat 5 Sep @ Dvořákova síň, Filarmonica della Scala / Chailly / Malofeev Sun 6 Sep, Magdalena Kožená & Kirill Gerstein Mon 7 Sep, Wiener Philharmoniker / Sokhiev / Hahn Sat 12 Sep. Paginate as /program/?page=N — NOTE THE TRAILING SLASH on /program/; requesting /program?page=2 without it silently returns page 1. Roughly 19 pages. Each card gives date, start time, hall (e.g. Dvořákova síň), title and a link /event/{id}-{slug}/, with an English mirror at /en/program and /en/event/{id}-{slug}/; the numeric {id} is identical across languages and is the dedupe key. Add /program-vystavy for Galerie Rudolfinum exhibitions, which are date RANGES and need range handling. Optional narrower feeds: /program-pro-deti, /program-prohlidky, /program-zive-prenosy. Times Europe/Prague.','www.rudolfinum.cz','src_0c7793fb',true,'render'),

  ('Ticketmaster Česká republika','celostátní','CZ','https://www.ticketmaster.cz/category/hudba-vstupenky/10001','HTML event listing',ARRAY['koncerty','hudba','divadlo a umění','kluby','festivaly','rodina','sport'],'robots.txt (updated 2023-02-27) has no Disallow for /category/, /event/ or /artist/ under "User-agent: *"; the blocked paths are transactional and API surfaces the collector must stay off — /checkout/, /search.php, /browse, /json/search/*, /api/ (except /api/quickpicks/ and /api/seatmap/), /seatmap/, /myAccount/*, /user/, /bba/, /video/, and */6025/*. GPTBot is fully disallowed, so never identify as GPTBot; Crawl-delay: 5 applies to msnbot only, but throttle conservatively anyway. Commercial ticketing data: collect factual fields (title, date, venue, city, link) and link back — do not mirror descriptions or artwork. Ticketmaster ToS restrict automated access generally; the sanctioned lower-risk route is the official Discovery API.',0,'Server-rendered paginated HTML category listings. Verified live: /category/hudba-vstupenky/10001 reports "12494 akce/akcí" with ON COMPANY TIME 6.9.2026 19:00 @ Rock Café Praha 1, Hollywood Vampires 6.9.2026 20:00 @ Sportovní hala FORTUNA, Mike Oldfield''s Tubular Bells 13.9.2026 @ O2 universum. Crawl all seven categories: hudba-vstupenky/10001, umeni-a-divadlo-vstupenky/10002, rodina-vstupenky/10003, sport-vstupenky/10004, kluby-vstupenky/10006, specialni-akce-vstupenky/10007, festivaly-vstupenky/10101, plus the /{cat}/{subcat}/{id}/events subgenre listings. Each card gives title, date + start time, city, venue and a link /event/{slug}/{id}; the numeric event id is the dedupe key. Check detail pages for JSON-LD Event before falling back to DOM selectors. FILTER OUT the upsell rows that share a parent event''s date — VIP Packages, Fast Track, Parking Ticket, VIP Upgrade — or they will duplicate real events. Dates are d.m.yyyy, Europe/Prague.','www.ticketmaster.cz','src_468d9029',true,'render'),

  -- ============================== PL ==============================
  ('Miasto Poznań – Urząd Miasta Poznania (Miejski Informator Multimedialny)','Poznań','PL','https://www.poznan.pl/mim/events/','HTML event listing',ARRAY['koncerty','teatr','wystawy','sport','dla dzieci','wykłady i spotkania','festiwale'],'Official municipal public-information portal of the City of Poznań. robots.txt has no Disallow covering /mim/events/ for "User-Agent: *" (the disallows are /mim/wspolne, /mim/public/socialnet/, /mim/socialnet/, /mim/print-view/, /mim/qrcode/, /mim/zipfile/, /tilecache/, /leading/, /mapa_geopoz/, /mim/plan/*, /mim/public/szukaj/, the BIP admin paths, /socialnet/ and /plan/). IMPORTANT: robots.txt sets Crawl-delay: 10 for all agents — throttle to at most one request per 10 seconds. Named bots are blocked (Amazonbot, Yandex, AhrefsBot, SemrushBot, DataForSeoBot, sentibot, dotbot, 008) but a generic own-branded UA is permitted. Sitemap at /sitemap.xml.',1,'Static HTML — no headless browser; a plain GET with a normal browser UA returns the full listing. Verified live: Parkrun Poznań 5 Sep 2026 09:00 @ Park Cytadela, VI Rajd po Zdrowie 5 Sep 09:00 @ Jezioro Malta, Narodowe Czytanie "Dziadów" 5 Sep 11:00 @ Biblioteka Raczyńskich, Lech Janerka 5 Sep 19:00 @ Dziedziniec Zamkowy. THE TRAILING SLASH IS REQUIRED — /mim/events 404s; always use the www host (the apex 302s). Two crawl axes: (a) the date-scoped pages /mim/events/YYYY-MM-DD/, whose rolling forward index the listing itself exposes — cleanest, and it gives an unambiguous date per event; (b) offset pagination /mim/events/2/, /mim/events/3/, … Extract links matching /mim/events/<slug>,<numeric-id>.html; the trailing numeric id is the dedupe key. Query params ?count=10|20|30&sort=new are supported. The /events/ segment is a CMS route name, not a language switch — treat all text as pl-PL. Prefer the date-index axis to keep request volume low under Crawl-delay: 10.','www.poznan.pl','src_08495713',true,'render'),

  ('Teatr Wielki - Opera Narodowa','Warszawa','PL','https://teatrwielki.pl/kalendarium/','HTML event listing',ARRAY['opera','balet','taniec','muzyka klasyczna','teatr','wydarzenia edukacyjne'],'robots.txt is absent — https://teatrwielki.pl/robots.txt returns HTTP 404 (the TYPO3 install serves its homepage body), so there is no machine-readable crawl restriction to violate. Publicly accessible performance schedule of a state-funded national cultural institution, published for audience information and ticket sales; no login, paywall or terms gate. Ingest factual data only (title, date, time, stage, ticket link) and link back; do not copy production synopses or photos — store a short excerpt plus the canonical URL. Scrape politely with an identifying UA.',0,'Server-rendered HTML calendar, no JS. Verified live: the 2026/2027 season calendar lists Kurtyna wspomnień 3 Sep 2026 11:00 @ Foyer dolne, Gala baletowa 12 Sep 19:00 @ Sala Moniuszki, Androidy 17 Sep 19:00 @ Sala Moniuszki, GUSTAV MAHLER 26 Sep 19:00 @ Sala Moniuszki. /kalendarium/ renders the current month; enumerate forward via the stable pattern /kalendarium/data/YYYY/MM (2025-10 through 2027-04 seen). Each performance links to /kalendarium/{season}/{slug}/termin/{YYYY-MM-DD}_{HH-MM}, so parse the exact start datetime straight out of the URL and cross-check it against the rendered row. Strip the "#Szczegoly@..." fragment when normalising and dedupe on slug+datetime, since the same URL appears with and without it. English mirror at /en/calendar/date/YYYY/MM. The venue is fixed (plac Teatralny 1) apart from guest stages — read the stage label rather than hardcoding it. Crawl a rolling 12-month window monthly at ~1 req/s.','teatrwielki.pl','src_0904f69d',true,'render'),

  ('Ticketmaster Polska','Cała Polska','PL','https://www.ticketmaster.pl/category/muzyka-bilety/10001','HTML event listing',ARRAY['koncerty','muzyka','festiwale','sport','teatr i sztuka','kluby','kabaret','rodzina'],'robots.txt (updated 2023-02-27) does NOT disallow /category/, /discover/ or /event/<slug>/<id> for "User-agent: *"; it blocks /api/, /browse, /search.php, /json/search/*, /queryHandler.php*, /checkout/, /myAccount/*, /user/, /seatmap/, /video/, */6025/* and the legacy /event.jhtml, /search.jhtml and /index.cfm — so the chosen endpoints are permitted but those paths are off limits. GPTBot is fully disallowed and msnbot carries Crawl-delay: 5, so use a clearly identified non-GPTBot UA and a conservative delay. Facts (title, date, time, venue, city) are not copyrightable; do not mirror editorial descriptions or artwork. Ticketmaster ToS restrict automated access generally — the sanctioned route is the official Discovery API.',0,'Server-rendered HTML listing cards. Verified live: /category/muzyka-bilety/10001 reports "12494 Nadchodzące wydarzenia" with Koncert Chopinowski 5.09.2026 14:30 @ Sala koncertowa Fryderyk Warszawa, Rap & Freestyle 5.09.2026 19:00 @ COS Torwar, Jacob Collier 7.09.2026 18:00 @ Klub Studio Kraków, Jamie Woon 8.09.2026 @ Klub Palladium. Enumerate the sibling categories for coverage: muzyka-bilety/10001, sztuka-i-teatr-bilety/10002, rodzina-bilety/10003, sport-bilety/10004, kluby-bilety/10006, wydarzenia-specjalne-bilety/10007, festiwale-bilety/10101, kabaret-bilety/10102; optionally cross-check the /discover/{warsaw,cracow,wroclaw,gdansk,katowice,lodz} hubs. NO visible pagination control on the category pages — results are lazy-loaded, so a plain fetch returns only the first window; plan for a headless render or a date-window parameter. STRONGLY PREFERRED alternative: the official Discovery API (app.ticketmaster.com/discovery/v2/events.json?countryCode=PL, free key) returns the same catalogue as clean paginated JSON with venue geo and classifications — cheaper, sanctioned and immune to markup churn; keep the HTML listing as a fallback. Filter out /artist/ URLs (catalogue pages, not events). Normalise to Europe/Warsaw.','www.ticketmaster.pl','src_b35bae0a',true,'render'),

  ('Urząd Miejski Wrocławia — wroclaw.pl (Go Wrocław)','Wrocław','PL','https://www.wroclaw.pl/go/wydarzenia','HTML event listing',ARRAY['muzyka i koncerty','teatr','sport i rekreacja','dla dzieci','rozrywka','wystawy','festiwale','bezpłatne wydarzenia'],'Official municipal portal of the City of Wrocław; all listing and detail pages are open, with no login, paywall or age gate. robots.txt has no Disallow covering /go/ or /go/wydarzenia for "User-agent: *" — the blocked paths are /go-light*, the RSS endpoints, /open-data/, /beta2/proxy/, /eoffice*, /WEB-INF/ and the New Relic */aggregate$ beacons — and no Crawl-delay is declared, so apply a voluntary 1-2 s delay and a self-identifying UA. Collect factual data only and link back to the wroclaw.pl detail page.',1,'Server-rendered HTML listing, no JS. Verified live: 237 events across the categories, including Sobota z Zielonym Wrocławiem 12.09 12:00 @ Polana Popowicka, Folwark zwierzęcy 30.09 19:00 @ Teatr Polski - Scena na Świebodzkim, Garden Beats by Hint 10.09 @ Hotel Puro, PEJA x DJ DECKS 14.11 19:00 @ A2 Centrum Koncertowe. Crawl /go/wydarzenia plus the category hubs /go/wydarzenia/{muzyka,teatr,sport-i-rekreacja,dla-dzieci,edukacja-i-rozwoj,rozrywka,bezplatne-wydarzenia-wroclaw}, following the numbered ?page=N pagination to exhaustion. Parse each card for title, the Polish date/time string ("Czwartek 08.10 o 19:00" — and resolve the relative labels "Dziś"/"Jutro" against the fetch date), venue, and the detail href /go/wydarzenia/<kategoria>/<numericId>-<slug>. The numeric id is the site''s own event id and the right dedupe key. Check detail pages for JSON-LD Event before falling back to DOM selectors. Multi-day items ("do 13.09") need range expansion or a single ranged record.','www.wroclaw.pl','src_ce538561',true,'render'),

  ('Stołeczne Biuro Turystyki (Warsaw Tourism Office) — Go2Warsaw','Warszawa','PL','https://go2warsaw.pl/co-gdzie-kiedy/','HTML event listing with schema.org JSON-LD',ARRAY['koncerty','festiwale','muzyka klasyczna','wystawy','teatr','sport','wydarzenia kulinarne','wydarzenia rodzinne'],'robots.txt permits it: "User-agent: * / Disallow: /wp-admin/ / Allow: /wp-admin/admin-ajax.php" — neither /co-gdzie-kiedy/ nor /events/ is disallowed, and two sitemaps are advertised. The publisher is a municipal public body publishing this calendar to promote attendance, so collection is aligned with its purpose, and the embedded schema.org markup is an explicit invitation to machine consumption. Event facts are not copyrightable, but the JSON-LD "description" fields are long editorial prose that IS — store a short snippet and link back to offers.url rather than republishing.',1,'JSON-LD (schema.org Event) — the jsonld recipe reads this directly, no HTML scraping needed. VERIFIED AGAINST THE WORKER''S OWN PARSER CONTRACT: one GET returned 490 KB containing 1034 <script type="application/ld+json"> blocks; all 1034 parsed with JSON.parse and all 1034 are @type=Event carrying name + startDate + location.name — e.g. GASTRO MIASTO na Placu Centralnym 2026-09-04 @ Plac Centralny, sanah NA STADIONACH 2026-09-04T22:00:00+02:00 @ PGE Narodowy, 22. Festiwal Skrzyżowanie Kultur 2026-09-11 @ Teatr Dramatyczny. Per event: startDate + endDate (ISO, sometimes date-only), location.@type=Place with location.name, offers.url = the canonical detail URL and the stable dedupe key, offers.price + priceCurrency ("0"/"PLN" for free), eventStatus, description. NOTE that location.address and location.image are usually empty strings — geocode from location.name, do not expect a street address. Caveat: the whole forward calendar is inlined, so the page is ~0.5 MB and should be fetched at most daily; that is the trade for one request covering the full horizon. Detail pages live at /events/<slug>/.','go2warsaw.pl','src_6e537963',true,'jsonld'),

  -- ============================== SI ==============================
  ('Mestna občina Maribor — Kultura Maribor (Napovednik kulturnih dogodkov)','Maribor','SI','https://kultura.maribor.si/napovednik/seznam/','JSON API (The Events Calendar REST v1)',ARRAY['kultura','glasba','koncerti','gledališče','ples','razstave','festivali','literatura'],'Public-sector municipal cultural calendar, freely accessible with no auth or paywall. https://kultura.maribor.si/robots.txt is "User-agent: * / Disallow:" — an empty Disallow, i.e. full crawl permitted — and advertises /sitemap_index.xml. The site also publishes deliberate machine-readable syndication endpoints (iCal via ?ical=1, RSS at /napovednik/feed/, and the open Tribe REST API), so redistribution of the listings is clearly intended. Scrape politely (1 req/s, identify the bot) and link back to the canonical /dogodek/ detail page.',1,'scrape_strategy=tribe. VERIFIED AGAINST THE WORKER''S OWN CODE PATH: scrapeTribeSource() derives {origin}/wp-json/tribe/events/v1/events from endpoint_url, and that exact call returned HTTP 200 with total=29, total_pages=6 and events carrying precisely the fields the adapter reads — title, start_date ("2026-09-06 10:30:00", local Europe/Ljubljana), venue.venue, venue.address, venue.city, url, image, description, cost. Live rows: Pihalni orkester Pošta Maribor 2026-09-06 10:30 @ Paviljon Mestnega parka, Črta 2026-09-08 20:00 @ Intimni oder GT22, Cikel ljudske glasbe #3 2026-09-12 19:00 @ Kulturni inkubator. NOTE the adapter''s price regex only recognises Ft/HUF, so price_min stays null for these EUR listings — harmless, but do not read a missing price as a parse failure. Fallbacks if the REST API is ever withdrawn: iCal at /napovednik/seznam/?ical=1, or the HTML listing where each entry is an .hentry article (title in h3.tribe-events-calendar-list__event-title > a, datetime and venue in the sibling tribe-events-calendar-list__event-* blocks, rel-next at /napovednik/seznam/page/N/). Multi-day events (e.g. Festival Najstarejše trte 24-27 Sep) are one record with a date range — expand or store as a range, and dedupe on the .url slug.','kultura.maribor.si','src_5223c77c',true,'tribe'),

  ('Mojekarte.si','Vsa Slovenija','SI','https://www.mojekarte.si/si/vstopnice.html','HTML event listing',ARRAY['glasba','koncerti','festivali','kultura','gledališče','opera','film','šport','otroci in družina'],'robots.txt permits the endpoint under "User-agent: *" — /si/vstopnice.html and /si/vstopnice/{n}.html are not disallowed — with Crawl-delay: 10, which the collector MUST honour (max 1 request per 10 s). Disallowed and to be avoided: */iskanje.html, */trazi.html, */search.html, every purchase step (*/nakup-korak-*.html, */nakup-placilo.html, …), the /get-*.xml feeds including /get-performances-all.xml, */albumi/, */media/, */basket/, the account and login paths, and the /de/, /it/ and /fr/ locale trees (the /si/ Slovenian tree is allowed). IMPORTANT CAVEAT: the file opens with a ~57-entry blocklist ending in "Disallow: /" that names AI and SEO crawlers explicitly — including ClaudeBot, anthropic-ai, Claude-Web, GPTBot, ChatGPT-User, OAI-SearchBot, CCBot, PerplexityBot, Google-Extended, Bytespider, SemrushBot and AhrefsBot. The collector must therefore NOT identify with any of those tokens; run it under a distinct honest Hobbeast UA, which falls under "User-agent: *". Commercial ticketing data: ingest metadata only and link back.',0,'MUST send a browser-like User-Agent — the default agent gets HTTP 403 (WebFetch did; curl with a Chrome UA returned 200) — plus Accept-Language: sl. Server-rendered HTML, no JS. Verified live: the listing reports "1-25 od 744" with sob., 5. sep. 2026 ob 10:00 Pravljice pod krošnjami @ vrt Galerije Krpan, 5. sep. ob 11:00 Bi se gnetli na tej metli? @ Veliki oder LGL, 5. sep. ob 19:30 Gorenjski slavček @ SNG Opera in balet, 5. sep. ob 20:00 ZHIVOTNI @ Gala Hala Metelkova. Root / 302s to /si.html; the Slovenian prefix is /si/ (NOT /sl/). Paginate via /si/vstopnice/{n}.html (25 per page, ~30 pages; the next link is li.pagination a.next). Each event is a div.perf-wrapper with data-analytics-id / -name / -brand (organizer); inside it the detail link /si/{slug}/vstopnice-{id}.html (the numeric id is the dedupe key), a date string "sob., 5. sep. 2026, ob 20:00" (multi-day runs render as "21. 5. 2026 - 30. 9. 2026"), a venue link /si/lokacija/{id}/{slug}.html, a genre link /si/zanr/{id}/{slug}.html and a price ("od: 12,00 EUR do: 50,00 EUR"). Sold-out and cancelled states are inline text (RAZPRODANO, "koncert je odpovedan") — read them. Cross-check completeness against the "N-M od TOTAL" counter. Do NOT use /si/iskanje.html (robots-disallowed). Throttle to 1 request / 10 s.','www.mojekarte.si','src_a797cdc1',true,'render'),

  ('Turizem Ljubljana (Ljubljana Tourism) — official tourist board of the City of Ljubljana','Ljubljana','SI','https://www.visitljubljana.com/sl/obiskovalci/prireditve','HTML event listing',ARRAY['festivali','glasba in koncerti','razstave','šport','sejmi in tržnice','kulinarika','kultura','družina','vodeni ogledi'],'robots.txt is "User-agent: * / Disallow: /admin/" — the events paths are permitted and no Crawl-delay is set. Public, unauthenticated official city tourist board site with no paywall or login. The collected fields are factual event data; descriptive prose must not be copied verbatim — store a short link-back to the source detail page instead. Slovenian public-sector body in EU jurisdiction, so the sui generis database right applies to bulk extraction: keep harvesting limited to the listing (an insubstantial part) and attribute the source. Recommend 1 request per 2-3 s, a descriptive UA with a contact URL, and a daily-or-less refresh.',1,'Server-rendered HTML, no JS. Verified live: Ljubljanski festival športa 5. 9. 2026 @ Tivoli, ARTish 5. 9. 2026 10:00-17:00 @ Gallusovo nabrežje, Nedeljski bolšji trg 6. 9. 2026 08:00-15:00 @ Breg, Odprta kuhna 11. 9. 2026 10:00-21:00 @ Pogačarjev trg, plus long-range entries (Knjižnica pod krošnjami 1. 6. - 13. 9. 2026). Parse the repeated event cards: title, date string, optional time range, detail href. Date formats: single "4. 9. 2026", range "1. 6. - 13. 9. 2026", time "10:00-21:00" — parse D. M. YYYY with the dot-space separator and expand ranges into start_date/end_date (Europe/Ljubljana). Follow /sl/obiskovalci/prireditve/prireditve-v-ljubljani/<slug> for venue, address, price and description; the slug is the dedupe key. Flag multi-month entries as ongoing rather than emitting one row per day. Optional /en/visitors/events/ mirror for English titles. Do NOT target /sl/obiskovalci/prireditve/prireditve-v-ljubljani/ directly — it is client-side rendered and returns zero events to a plain fetcher. The congress calendar at /sl/kongresni-urad-ljubljane/koledar-kongresov is a separate B2B feed and must not be merged into this source.','www.visitljubljana.com','src_02eba0e6',true,'render'),

  -- ============================== SK ==============================
  ('Kam do mesta','Celoslovensky','SK','https://kamdomesta.sk/koncerty','HTML event listing',ARRAY['koncerty','predstavenia','divadlo','filmy','festivaly','kurzy','podujatia pre deti'],'https://kamdomesta.sk/robots.txt returns HTTP 200 with a ZERO-BYTE body — no User-agent groups, no Disallow rules, no Crawl-delay — so nothing in robots.txt restricts /koncerty or the sibling category listings. Publicly accessible, no login or paywall. Ingest factual event data only (title, date, time, city, venue); do not copy descriptive blurbs or press-release text verbatim. The site publishes terms at /content/obchodne-podmienky-a-gdpr which should be reviewed for an explicit anti-scraping clause before any high-volume crawling; until then stay well under 1 req/s with an identifying User-Agent.',0,'Static server-rendered HTML, plain GET, no JS. Crawl the apex host (www 301s to it). Verified live: the page heading is "Koncerty" and it lists ~16-17 dated rows grouped by day (Saturday 5 September 2026 and Sunday 6 September 2026) behind a "Zobraziť viac" control — e.g. Kaschauer Klezmer Band 5.9. 17:00 Bratislava-Čunovo, Eniesa & Martin Geišberg 5.9. 19:00 Poprad, Diana Damrau & Slovenská filharmónia 6.9. 19:00 Bratislava-Ružinov. Each card exposes title, DD.MM.YYYY + start time, city, and a venue link /miesto/<venue-slug> usable for enrichment. For coverage enumerate the sibling category listings sharing the template: /koncerty, /predstavenia, /kurzy, /deti-a-mladez, /sutaze, /kina/slovensko/. Do NOT use /podujatia (302 to /) and do NOT use the homepage — it is a featured "Top podujatia" view that collapses tours into aggregate counts ("6 dates", "57 dates") instead of individual dated rows. Exclude /tlacove-spravy/* (press releases) and /prihlasenie/*. Dates are day-first; Europe/Bratislava, sk-SK.','kamdomesta.sk','src_e3735466',true,'render'),

  ('Slovenské národné divadlo (Slovak National Theatre)','Bratislava','SK','https://snd.sk/program','HTML event listing',ARRAY['divadlo','činohra','opera','balet','tanec'],'robots.txt is standard Drupal 7 boilerplate disallowing only /admin/, /search/, /modules/, /themes/, /includes/, /profiles/, /scripts/, /node/add/, /comment/reply/, the user auth paths and the CHANGELOG/INSTALL text files — /program and /predstavenie/* are NOT disallowed. IMPORTANT: robots.txt sets Crawl-delay: 10, so throttle to at most one request per 10 seconds. Publicly accessible, non-authenticated programme of a state-funded national cultural institution; no paywall or login, and no ToS-level scraping prohibition was observed on the listing page. Extract factual fields only (title, date, time, venue, genre) — production synopses and photos are copyrighted.',0,'Static server-rendered HTML (Drupal 7), no JS. Verified live: the September 2026 programme lists Život Galileiho Sat 5 Sep 19:00 @ Nová budova - Sála činohry, Watsonovci Tue 8 Sep 10:00, Krútňava Wed 9 Sep 19:00 @ Sála opery a baletu, Figarova svadba Thu 17 Sep 18:00, Romeo a Júlia Fri 25 Sep 19:00. Parse anchors matching href="/predstavenie/{id}/{YYYY-MM-DD}/{HH-MM}/{slug}/{YYYY-MM-DD}/{HH-MM}" — the URL itself encodes the performance id, ISO date and start time, so date, time and slug come free without fetching detail pages. Title from the anchor text, stage from the surrounding row (Nová budova / Historická budova / Sála opery a baletu). No JSON-LD, so rely on the URL pattern rather than structured data. /program shows one month at a time (43 performances for 2026-09); widen with the program-season select and the genre listings /program-cinohra, /program-opera, /program-balet. DEDUPE BY PERFORMANCE ID: the crawl found several URL aliases per performance (/predstavenie/, /performance/, /en/performance/, /de/buhnendarstellung/, plus duplicated date/time segments). Honour Crawl-delay: 10.','snd.sk','src_711dc73e',true,'render'),

  ('Predpredaj.sk (Zoznam)','Celoslovensky','SK','https://predpredaj.zoznam.sk/sk/','HTML event listing',ARRAY['koncerty','divadlo','festivaly','šport','show','pre deti','ostatné'],'https://predpredaj.zoznam.sk/robots.txt (HTTP 200) is permissive: "User-agent: *" with only five Disallow rules, all of them legacy 2020 event slugs (lorna-byrne-*, tomas-klus-*, floriansky-beh-bez-barier). Neither /sk/ nor /sk/kategoria/ nor /sk/listky/ is disallowed and no Crawl-delay is set; apply a polite self-imposed rate anyway and skip those five slugs. Public listing and event pages, no login or paywall. NOTE that the registered host is the predpredaj.zoznam.sk subdomain, not predpredaj.sk — the brand name and the serving host differ, and dedupe must key on the serving host.',0,'Server-rendered static HTML, plain GET with a browser UA; no JSON-LD and no schema.org itemtype, so parse the DOM. Verified live: Symfónia umenia 31.8.-6.9.2026 Bratislava, HK Nitra - Växjö Lakers 6.9.2026 17:00 @ Tiposbet Arena, UNBROS MUSIC FESTIVAL 18.9.2026 17:00 @ TIPOS Aréna, International Autoshow 19.-20.9.2026 @ Incheba. Seed from /sk/ (broadest) plus the seven /sk/kategoria/<slug>/ pages and /sk/futbal/, /sk/hokejova-extra-liga/; dedupe by slug. Collect links matching href="/sk/listky/<slug>/". DO NOT TRUST THE CARD DATE ALONE — it comes in three shapes: exact ("04.02.2027 20:00"), range ("31.08. - 06.09.2026") and fuzzy tour labels ("November - December", venue "Slovensko"). Instead strip the trailing slash and append .ics to the event URL and read DTSTART/SUMMARY/UID (verified working); fall back to the card text only if the .ics 404s. The .ics UID (e.g. 51665.event.events.sk.predpredaj) or the slug is the stable external id. Treat tour-parent pages (/sk/listky/apostol-koncerty-2026/) as containers and follow their dated children. Skip /sk/stranka/*, /sk/uzivatel/*, /sk/darcekove-poukazy/, /sk/backstage/ and /en/get-sector-data/*, and use /sk/zrusene-podujatia/ only as a suppression list.','predpredaj.zoznam.sk','src_61b36ef4',true,'render'),

  ('Bratislava Tourist Board (Bratislavská organizácia cestovného ruchu) — Visit Bratislava','Bratislava','SK','https://www.visitbratislava.com/sk/podujatia','HTML event listing',ARRAY['hudba a koncerty','divadlo a zábava','tanec','gastronómia','festivaly','výstavy','nočný život','trhy a jarmoky','šport','rodina'],'robots.txt disallows only WordPress system paths (/wp-admin/, /wp-content/, /wp-includes/, /comment-page-, /trackback/, /xmlrpc.php, /blackhole/, /mint/, /feed/) and declares /sitemap_index.xml — the event paths are permitted. No Crawl-delay is specified, so use a polite self-imposed delay. Official destination-marketing portal of the Bratislava Tourist Board, publishing third-party event listings for promotional reach, which is consistent with linking back to the detail page. Collect factual data and link out rather than republishing full descriptions or photos, which remain the organisers'' copyright. NOTE: no Terms-of-Service page was reviewed in either vetting pass — re-check the ToS before any bulk or high-frequency ingestion.',1,'Server-rendered WordPress HTML (theme "visitbratislava"), a plain parser is enough, no JS. Verified live: Fest Čierny Deň 2026 5.9. @ Mlynice, Trh – Piac – Markt 5.9. @ Stará tržnica, Castle Flow 2026 5.9. @ Bratislavský hrad, Živé Račko 2026 5.9. @ Park na Račianskom mýte, Dni majstrov ÚĽUV 5.-6.9. @ Staré Mesto. Iterate /sk/podujatia/page/{N} for N=1..~24 (page 1 is the bare /sk/podujatia URL); stop when a page yields zero cards or repeats the previous page''s slugs. Each card exposes the title, a visible date or range ("5. 9." or "5.-6. 9.") and a detail link /sk/podujatia/<slug>; follow it for venue, time, price and description. THE YEAR IS USUALLY IMPLICIT in the card date — anchor parsing to the current year and roll forward when the month is earlier than today. Category facets at /sk/{lang}/event-categories/<slug>. Crawl the /sk/ tree as primary (~24 pages, about double the English mirror''s 12) and optionally use /events for English titles keyed by slug+date. Dedupe by detail-page slug. Because it is WordPress, probe /wp-json/wp/v2/ once for a podujatia custom-post-type endpoint — if present it gives clean JSON and should be preferred over HTML scraping.','www.visitbratislava.com','src_f6e5263d',true,'render')

) AS v(
  publisher_name, city, country_code, endpoint_url, format, categories, legal_basis,
  dedupe_priority, parser_strategy, host, source_id, scrape_enabled, scrape_strategy
)
-- Host guard: never register a host the collector already has, whatever id it carries.
-- ON CONFLICT only protects source_id, and the V5 lesson stands — dedupe on the FINAL
-- endpoint host, not the name the crawl arrived with (predpredaj.sk resolves to
-- predpredaj.zoznam.sk, and musikverein.at's calendar lives on spielplan.musikverein.at).
WHERE NOT EXISTS (
  SELECT 1 FROM public.external_event_feed_sources existing
  WHERE existing.endpoint_url IS NOT NULL
    AND lower(regexp_replace(split_part(regexp_replace(existing.endpoint_url, '^https?://', ''), '/', 1), '^www\.', ''))
      = lower(regexp_replace(v.host, '^www\.', ''))
)
ON CONFLICT (source_id) DO NOTHING;
