// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { FunctionInvokeOptions, FunctionInvokeResult } from '@supabase/supabase-js';
import type { Database } from './types';

/**
 * IMPORTANT:
 * All web-app database queries and Edge Function calls must target the dsymdijzydaehntlmfzl
 * Supabase project via the VITE_* frontend environment variables.
 */
const SUPABASE_URL = String(import.meta.env.VITE_SUPABASE_URL || '').replace(/\/+$/, '');
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

export async function invokeFunctionWithDebug<T = unknown>(
  functionName: string,
  options?: FunctionInvokeOptions,
): Promise<FunctionInvokeResult<T>> {
  const requestUrl = `${SUPABASE_URL}/functions/v1/${functionName}`;
  const {
    data: { session },
  } = await supabase.auth.getSession();

  const authHeader = session?.access_token ? { Authorization: `Bearer ${session.access_token}` } : {};
  console.info('[EdgeInvoke] invoking', {
    functionName,
    requestUrl,
    hasAuthorizationHeader: Boolean(session?.access_token),
  });

  const result = await supabase.functions.invoke<T>(functionName, {
    ...options,
    headers: {
      ...(options?.headers || {}),
      ...authHeader,
    },
  });

  if (result.error) {
    console.error('[EdgeInvoke] failed', {
      functionName,
      requestUrl,
      error: result.error,
      body: options?.body,
    });
  }

  return result;
}
