// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { FunctionInvokeOptions, FunctionInvokeResult } from '@supabase/supabase-js';
import type { Database } from './types';

/**
 * IMPORTANT:
 * All web-app database queries and Edge Function calls must target the dsymdijzydaehntlmfzl
 * Supabase project via the VITE_* frontend environment variables.
 */
const SUPABASE_URL = String(import.meta.env.VITE_SUPABASE_URL || '').replace(/\/+$/, '');
const SUPABASE_PUBLISHABLE_KEY = String(import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || '');

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

export async function invokeFunctionWithDebug<T = unknown>(
  functionName: string,
  options?: FunctionInvokeOptions,
): Promise<FunctionInvokeResult<T>> {
  const requestUrl = `${SUPABASE_URL}/functions/v1/${functionName}`;
  const {
    data: { session },
  } = await supabase.auth.getSession();

  // The Supabase function gateway always requires the project anon key in
  // the `apikey` header for routing — even when the function itself has
  // verify_jwt = false. The Authorization header carries the user JWT
  // (used for RLS context) when present.
  const baseHeaders: Record<string, string> = {};
  if (SUPABASE_PUBLISHABLE_KEY) baseHeaders.apikey = SUPABASE_PUBLISHABLE_KEY;
  if (session?.access_token) {
    baseHeaders.Authorization = `Bearer ${session.access_token}`;
  } else if (SUPABASE_PUBLISHABLE_KEY) {
    // Fall back to the publishable key so the gateway never rejects on
    // missing Authorization (e.g. anonymous admin smoke checks).
    baseHeaders.Authorization = `Bearer ${SUPABASE_PUBLISHABLE_KEY}`;
  }

  console.info('[EdgeInvoke] invoking', {
    functionName,
    requestUrl,
    hasAuthorizationHeader: Boolean(baseHeaders.Authorization),
    hasApikeyHeader: Boolean(baseHeaders.apikey),
  });

  const result = await supabase.functions.invoke<T>(functionName, {
    ...options,
    headers: {
      ...baseHeaders,
      ...(options?.headers || {}),
    },
  });

  if (result.error) {
    console.error('[EdgeInvoke] failed', {
      functionName,
      requestUrl,
      error: result.error,
      body: options?.body,
    });
  }

  return result;
}
